apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: acm-custom-registry
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  address: acm-custom-registry.open-cluster-management.svc:50051
  displayName: "Customer Operators"
  image: quay.io/acm-d/acm-custom-registry:2.3.0-DOWNSTREAM-2021-04-24-05-15-03
  updateStrategy:
    registryPoll:
      interval: 10m0s